### ISSUE TITLE
Runs on NASBench201

### ISSUE THREAD

**Issue by matteogambella** [dr-faustus/Lambda-DARTS#3]
I saw the code to run on DARTS search spaces is available but I cannot find the code to run on NASBench201, how can I replicate the results on Table 1 (NasBench201)?

**Comment by dr-faustus** [comment]
Hi! Thank you for reaching out.
You can find the code for NASBench201 in the repository. All you have to do is download the performance table from the link provided in the README.md file (Datasets section, last bullet point). Afterward, you can run a search and evaluation experiment by running the NAS-Bench201/exps/algos/DARTS-V1.py file with the correct hyperparameters mentioned in the paper (make sure you set the flag corr_regularization to true). Please let us know if you face any other issues.

**Comment by matteogambella** [comment]
Okk, thank you for the quick reply!
